name: Periodic Django Management Commands

on:
  schedule:
    - cron: "0 */2 * * *"  # Runs at 0th min past every 2 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true  # Required for pushing changes
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Django Management Commands
      working-directory: ./access_amherst_backend
      run: |
        python manage.py hub_workflow
        python manage.py calendar_workflow
        python manage.py remove_old_events
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "ran periodic workflow for db update"
        git push
